// React/tictactoe.js
class Game extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      history: [
        {
          squares: Array(9).fill(null)
        }
      ],
      stepNumber: 0,
      xIsNext: true
    };
  }

  handleClick(i) {
    const history = this.state.history.slice(0, this.state.stepNumber + 1);
    const current = history[history.length - 1];
    const squares = current.squares.slice();
    if (calculateWinner(squares) || squares[i]) {
      return;
    }
    squares[i] = this.state.xIsNext ? "X" : "O";
    this.setState({
      history: history.concat([
        {
          squares: squares
        }
      ]),
      stepNumber: history.length,
      xIsNext: !this.state.xIsNext
    });
  }

  jumpTo(step) {
    this.setState({
      stepNumber: step,
      xIsNext: (step % 2) === 0
    });
  }

  render() {
    const history = this.state.history;
    const current = history[this.state.stepNumber];
    const winner = calculateWinner(current.squares);

    const moves = history.map((step, move) => {
      const desc = move ?
        'Go to move #' + move :
        'Go to game start';
      return (
        <li key={move}>
          <button onClick={() => this.jumpTo(move)}>{desc}</button>
        </li>
      );
    });

    let status;
    if (winner) {
      status = "Winner: " + winner;
    } else {
      status = "Next player: " + (this.state.xIsNext ? "X" : "O");
    }

    return (
      <div className="game">
        <div className="game-board">
          <Board
            squares={current.squares}
            onClick={i => this.handleClick(i)}
          />
        </div>
        <div className="game-info">
          <div>{status}</div>
          <ol>{moves}</ol>
        </div>
      </div>
    );
  }
}
  
// ========================================
  
ReactDOM.render(<Game />, document.getElementById("root"));

// Lit-JS/tictactoe.js
import {LitElement, html, css} from 'https://cdn.jsdelivr.net/gh/lit/dist@2.2.1/core/lit-core.min.js'
import {calculateWinner} from "./helper.js"
import { tictactoeStyles } from './css.js';
import "./board.js";

export class Game extends LitElement {
    constructor() {
        super();
        this.history = [{
            squares: Array(9).fill("")
        }];
        this.xIsNext = true;
        this.stepNumber = 0;
    }

    // callbacks

    handleClick(i) {
        const history = this.history.slice(0, this.stepNumber + 1);
        const current = history[history.length - 1];
        
        if (calculateWinner(current.squares) || current.squares[i])
            return

        const squares = current.squares.slice();
        squares[i] = this.xIsNext ? "X" : "O";

        this.history = history.concat([{
            squares: squares
        }])
        this.xIsNext = ! this.xIsNext;
        this.stepNumber = history.length;

        this.requestUpdate();
    }

    jumpTo(step) {
        this.stepNumber = step;
        this.xIsNext = (step % 2) === 0;

        this.requestUpdate();
    }

    // == html rendering ==
    
    static styles = tictactoeStyles

    render() {
        const current = this.history[this.stepNumber];
        const winner = calculateWinner(current.squares);
        const status =
            winner
            ? `Winner: ${winner}`
            : `Next player: ${this.xIsNext ? 'X' : 'O'}`;

        const moves = 
            this
            .history
            .map((step, move) => {
                var desc = move
                    ? 'Go to move #' + move
                    : 'Go to game start';
                desc = move == this.stepNumber
                    ? html `<b>${desc}</b>`
                    : desc
                return html `
                    <li>
                        <button class="history" @click=${() => this.jumpTo(move)}>
                            ${desc}
                        </button>
                    </li>`;})

        return html `
            <div class="game">
                <div class="game-board">
                    <board-world
                        squares=${JSON.stringify(current.squares)} .onClick=${(i) => this.handleClick(i)}>
                    </board-world>
                </div>
                <div class="game-info">
                    <div class="status">${status}</div>
                    <ol>${moves}</ol>
                </div>
            </div>`
    }
}

customElements.define( 'game-world', Game );
